### ISSUE TITLE
No fetching backend available

### ISSUE THREAD

**Issue by zoffixznet** [ugexe/zef#86]
Can't install modules after a clean `rm -fr ~/.perl6; rm -fr ~/.rakudobrew/; git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew; rakudobrew build moar; rakudobrew build zef;`

Getting the error that no fetching backends are available. Knowing a bit about `zef` I have an idea of what that might mean, but it may be useful to tell the user how they could fix it in the error message (or pre-install the backend somehow)

```
$ zef install App::ModuleSnap
===> Searching for: App::ModuleSnap
===> Searching for missing dependencies: META6
===> Searching for missing dependencies: JSON::Class
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Fast, JSON::Name
===> Fetching: App::ModuleSnap
No fetching backend available
  in method fetch at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/9A7F6D9DC63DB9D16EA19A61EED98CA9388F61B6 line 10
  in code  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 159
  in method fetch at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 138
  in sub MAIN at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 147
  in block <unit> at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/21D746CFA68C6190C43E2F84F56A4DF747BA50FA line 1
```

That occured on two boxes:
```
Linux HOST 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```
and

```
Linux HOST 3.2.0-4-686-pae #1 SMP Debian 3.2.51-1 i686 GNU/Linux
```

**Comment by zoffixznet** [comment]
Here's more debug info:
```
$ ZEF_PLUGIN_DEBUG=1 zef install App::ModuleSnap
===> Searching for: App::ModuleSnap
[Plugin - cached] Checking: Zef::ContentStorage::LocalCache
[Plugin - cached] 	(OK) Plugin loaded successful
[Plugin - cached] (OK) Plugin is now usable: Zef::ContentStorage::LocalCache
[Plugin - p6c] Checking: Zef::ContentStorage::P6C
[Plugin - p6c] 	(OK) Plugin loaded successful
[Plugin - p6c] (OK) Plugin is now usable: Zef::ContentStorage::P6C
[Plugin - cpan] Checking: Zef::ContentStorage::CPAN
[Plugin - cpan] 	(SKIP) Not enabled
===> Searching for missing dependencies: META6
===> Searching for missing dependencies: JSON::Class
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Fast, JSON::Name
===> Fetching: App::ModuleSnap
[Plugin - git] Checking: Zef::Shell::git
[Plugin - git] 	(OK) Plugin loaded successful
[Plugin - git] 	(OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Shell::git
[Plugin - path] Checking: Zef::Fetch::Path
[Plugin - path] 	(OK) Plugin loaded successful
[Plugin - path] 	(OK) Probing successful
[Plugin - path] (OK) Plugin is now usable: Zef::Fetch::Path
[Plugin - wget] Checking: Zef::Shell::wget
[Plugin - wget] 	(OK) Plugin loaded successful
[Plugin - wget] 	(OK) Probing successful
[Plugin - wget] (OK) Plugin is now usable: Zef::Shell::wget
[Plugin - curl] Checking: Zef::Shell::curl
[Plugin - curl] 	(OK) Plugin loaded successful
[Plugin - curl] 	(OK) Probing successful
[Plugin - curl] (OK) Plugin is now usable: Zef::Shell::curl
[Plugin - pswebrequest] Checking: Zef::Shell::PowerShell::download
[Plugin - pswebrequest] 	(OK) Plugin loaded successful
[Plugin - pswebrequest] 	(SKIP) Probing failed
No fetching backend available
  in method fetch at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/9A7F6D9DC63DB9D16EA19A61EED98CA9388F61B6 line 10
  in code  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 159
  in method fetch at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 138
  in sub MAIN at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 147
  in block <unit> at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/21D746CFA68C6190C43E2F84F56A4DF747BA50FA line 1
```

**Comment by ugexe** [comment]
Resolved in b2a917f

This issue is caused by `Zef::Identity` and `Zef::Shell::git` not recognizing `git@` as a valid URI scheme to use. The default p6c ecosystem list mangles these to `git://`, but the default mirror does not (see: https://github.com/ugexe/zef/blob/master/resources/config.json#L26-L27 # todo: make these switchable from CLI). I've left the mirror alone, but zef now mangles these ssh style non-uri-rfc-conforming uris to a valid uri using `ssh://git@...`

There is an additional issue related installing the module from the example that can be viewed here:
https://github.com/jonathanstowe/App-ModuleSnap/issues/1
This can be worked around by using `--depsonly` first until the test noted in the issue is adjusted to use the entire `$*REPO` chain

**Comment by jonathanstowe** [comment]
I have just removed the test, it doesn't make sense to include modules that *may* be installed as a dependency in the test.

**Comment by zoffixznet** [comment]
Seems the issue is still present. I completely nuked everything and started from scratch, yet still a failure. It's only with App::ModuleSnap. I tried installing App::Nopaste and that succeeded fine. Here's the output, which I believe is same as before:

```
$ ZEF_PLUGIN_DEBUG=1 zef install App::ModuleSnap
===> Searching for: App::ModuleSnap
[Plugin - cached] Checking: Zef::ContentStorage::LocalCache
[Plugin - cached] 	(OK) Plugin loaded successful
[Plugin - cached] (OK) Plugin is now usable: Zef::ContentStorage::LocalCache
[Plugin - p6c] Checking: Zef::ContentStorage::P6C
[Plugin - p6c] 	(OK) Plugin loaded successful
[Plugin - p6c] (OK) Plugin is now usable: Zef::ContentStorage::P6C
[Plugin - cpan] Checking: Zef::ContentStorage::CPAN
[Plugin - cpan] 	(SKIP) Not enabled
===> Searching for missing dependencies: META6
===> Searching for missing dependencies: JSON::Class
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Fast, JSON::Name
===> Fetching: App::ModuleSnap
[Plugin - git] Checking: Zef::Shell::git
[Plugin - git] 	(OK) Plugin loaded successful
[Plugin - git] 	(OK) Probing successful
[Plugin - git] (OK) Plugin is now usable: Zef::Shell::git
[Plugin - path] Checking: Zef::Fetch::Path
[Plugin - path] 	(OK) Plugin loaded successful
[Plugin - path] 	(OK) Probing successful
[Plugin - path] (OK) Plugin is now usable: Zef::Fetch::Path
[Plugin - wget] Checking: Zef::Shell::wget
[Plugin - wget] 	(OK) Plugin loaded successful
[Plugin - wget] 	(OK) Probing successful
[Plugin - wget] (OK) Plugin is now usable: Zef::Shell::wget
[Plugin - curl] Checking: Zef::Shell::curl
[Plugin - curl] 	(OK) Plugin loaded successful
[Plugin - curl] 	(OK) Probing successful
[Plugin - curl] (OK) Plugin is now usable: Zef::Shell::curl
[Plugin - pswebrequest] Checking: Zef::Shell::PowerShell::download
[Plugin - pswebrequest] 	(OK) Plugin loaded successful
[Plugin - pswebrequest] 	(SKIP) Probing failed
No fetching backend available
  in method fetch at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/9A7F6D9DC63DB9D16EA19A61EED98CA9388F61B6 line 10
  in code  at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 159
  in method fetch at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/1DC0BAA246D0774E7EB4F5119C6168E0D8266EFA (Zef::Client) line 138
  in sub MAIN at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/sources/A9948E7371E0EB9AFDF1EEEB07B52A1B75537C31 (Zef::CLI) line 147
  in block <unit> at /home/zoffix/.rakudobrew/moar-nom/install/share/perl6/site/resources/21D746CFA68C6190C43E2F84F56A4DF747BA50FA line 1
```

**Comment by jonathanstowe** [comment]
I've changed the source url anyway so it'll be all good when it filters through

**Comment by ugexe** [comment]
Odd, it's behavior is indicative of old code. I'll investigate further, but maybe deleting ~/.perl6 would solve it (it's the only way I can think of old code getting loaded despite nuking rakudo... Possibly dynamically loaded plugins not invalidating old precomp?)

App::NoPaste uses a 'git://' prefix (which is a valid rfc URI) and should have worked before https://github.com/ugexe/zef/commit/b2a917f8e0523c46dab336bb4b6a14bf50b3933c as only the ssh variant 'git@xxx:' prefix was not understood previously

**Comment by zoffixznet** [comment]
My `update-perl6` command is an alias for this `rm -fr ~/.perl6; rm -fr ~/.rakudobrew/; git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew; rakudobrew build moar; rakudobrew build zef;`

That should nuke both `~/.perl6` and `~/.rakudobrew` and install fresh zef, I believe.

**Comment by ugexe** [comment]
Jokes on me, I think *my* precomps were not updated. The original fix, after I confirmed it worked, was moved a few lines down into a conditional using `m//` instead of its original [S///](http://blogs.perl.org/users/zoffix_znet/2016/04/perl-6-the-s-operator.html). I retested and it still worked, but actually looking at the code it's clear to me it should not have. After nuking my files I received the same error as @zoffixznet, meaning the changes I made were not accounted for during precomp invalidation.
